Optional authenticity token nt
beautifulruby/superform pull request #38
Opened 2024-05-19 04:13 UTC by nolantait

Rails [doesn't check](https://stackoverflow.com/a/1571900) GET requests for `authenticity_token`. Currently if you make GET requests the token will be littered in the URL. Rails also has the [same option](https://api.rubyonrails.org/v7.1.3.3/classes/ActionView/Helpers/FormHelper.html#method-i-form_for-label-Form+to+external+resources).

I also added some docs in the README. This change also contains some feedback I got from my friend who was reading the docs and got confused about `#row` mentions in the README. I've changed them to `#labelled` so they are unified.

This PR also adds `phlex-testing-capybara` which is quite familiar to rails devs and could help make writing specs for rails components more approachable. Its still a bit awkward to magically stub `helpers` in the tests but they work and are easy to write.

Happy for any feedback

2024-05-20 19:36 UTC, bradgessler commented
Thanks for contributing! I'd rather eliminate the configuration and instead not include the authenticity token for a `GET` request.

Here's the steps that would take:

1. Remove the `:authenticity_token` option from the constructor.
2. Create a protected method within Superform like `def has_authenticity_token? = form_method != "get"`
3. Add a check to the form template that looks something like `authenticity_token_field if has_authenticity_token?`

If you include specs for all that and I can merge it.

For the docs, you can tell people they can force that field for get requests by overriding the method like this: `has_authenticity_token? = true`

Could you put the `row`/`labeled` changes in a different PR? I like keeping PRs related to one issue so the conversation doesn't fork.

2024-06-12 19:33 UTC, nolantait commented
Sounds good, I've removed the docs changes in this PR. Not sure what I buggered with the Gemfile.lock for the CI.

2024-12-05 18:37 UTC, bradgessler requested changes
I've thought more about this and I think the changes can be as simple as modifying the `authenticity_token` method to check if the `action` resolves to `GET`. The user could override the token in a subclass per the comment in the review.

The principal behind removing this from the constructor is I don't want to include non-html attributes in it. The constructor should feel like a `Form` field is being built; adding `authenticity_token` to it implies the HTML that would emit is `<form authenticity-token/>`, which is not the case.

2024-12-05 18:37 UTC, bradgessler commented on Gemfile
> +gem "phlex-testing-capybara", "~> 0.1.0"
Please remove this gem; specs can be implemented within the existing suite.

2024-12-05 18:37 UTC, bradgessler commented on Gemfile.lock
> -    actioncable (7.0.6)
Please rollback the bundle update. Shouldn't be necessary for this change and it obscures the PR.

2024-12-05 18:37 UTC, bradgessler commented on spec/superform/rails/form_spec.rb
> +RSpec.describe Superform::Rails::Form, type: :rails do
I don't want to use mocking or specs in the test quite; it makes it harder to understand and these can be implemented more concretely with the existing suite.

2024-12-05 18:37 UTC, bradgessler commented on lib/superform/rails.rb
> +      def initialize(model, action: nil, method: nil, authenticity_token: true, **attributes)
I've thought about this and I don't think this should be in the constructer. Instead it should be a method that excludes the token if the `method` resolves to `GET`. If the user doesn't want that, they could override the method to:

```
def authenticity_token_field = nil
```

2025-08-22 21:05 UTC, closed without merging